# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f0505d3646f5510b29cbea53ae15edd4"
name = "TrackFlow"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_pixels,write_pixels"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
